export default function loadNewUsers() {
  const usersContainer = document.createElement('div');
  usersContainer.classList.add('usersContainer');
  const banner = document.createElement('div');
  banner.innerText = 'Nuevos Usuarios';
  banner.classList.add('bannerUsers');
  const user = document.createElement('div');
  user.classList.add('user');
  const userOne = document.createElement('div');
  userOne.classList.add('user');
  const userTwo = document.createElement('div');
  userTwo.classList.add('user');
  const userThree = document.createElement('div');
  userThree.classList.add('user');
  const userFour = document.createElement('div');
  userFour.classList.add('user');
  const userName = document.createElement('a');
  userName.innerText = 'Maria Contreras';
  userName.classList.add('userName');
  const userImage = document.createElement('img');
  userImage.classList.add('userImage');
  userImage.alt = userName;
  userImage.src = 'https://i.postimg.cc/SKH0JgLj/img.png';
  const userNameOne = document.createElement('a');
  userNameOne.innerText = 'Alejandro Reyes';
  userNameOne.classList.add('userName');
  const userImageOne = document.createElement('img');
  userImageOne.classList.add('userImage');
  userImageOne.alt = userName;
  userImageOne.src = 'https://i.postimg.cc/9f3yK0rn/Mask-group.png';
  const userNameTwo = document.createElement('a');
  userNameTwo.innerText = 'Maggie Sarmiento';
  userNameTwo.classList.add('userName');
  const userImageTwo = document.createElement('img');
  userImageTwo.classList.add('userImage');
  userImageTwo.alt = userName;
  userImageTwo.src = 'https://i.postimg.cc/d1gyxM8w/Maggie.png';
  const userNameThree = document.createElement('a');
  userNameThree.innerText = 'Paulette Villegas';
  userNameThree.classList.add('userName');
  const userImageThree = document.createElement('img');
  userImageThree.classList.add('userImage');
  userImageThree.alt = userName;
  userImageThree.src = 'https://i.postimg.cc/5NxG2Dhs/Mask-group.png';
  const userNameFour = document.createElement('a');
  userNameFour.innerText = 'Skarlet Araque';
  userNameFour.classList.add('userName');
  const userImageFour = document.createElement('img');
  userImageFour.classList.add('userImage');
  userImageFour.alt = userName;
  userImageFour.src = 'https://i.postimg.cc/g0R4DD9w/Mask-group.png';

  user.appendChild(userImage);
  user.appendChild(userName);
  userOne.appendChild(userImageOne);
  userOne.appendChild(userNameOne);
  userTwo.appendChild(userImageTwo);
  userTwo.appendChild(userNameTwo);
  userThree.appendChild(userImageThree);
  userThree.appendChild(userNameThree);
  userFour.appendChild(userImageFour);
  userFour.appendChild(userNameFour);
  usersContainer.appendChild(banner);
  usersContainer.appendChild(user);
  usersContainer.appendChild(userOne);
  usersContainer.appendChild(userTwo);
  usersContainer.appendChild(userThree);
  usersContainer.appendChild(userFour);
  return usersContainer;
}
